/*
 * EPW Insights
 * Author: Ehsan Rostami (https://github.com/ehsan-rostami)
 * Copyright (c) 2025-2026 Ehsan Rostami
 * Released under the GNU Affero General Public License v3.0 or later.
 */

import { describe, it, expect } from 'vitest';
import { parseEPW } from './epw-parser';

describe('EPW Parser', () => {
  it('should parse standard location metadata correctly', () => {
    const mockEpw = `LOCATION,Tehran,Tehran,IRN,SYN,407540,35.68,51.32,3.5,1191.0
DESIGN CONDITIONS,1
TYPICAL/EXTREME PERIODS,2
GROUND TEMPERATURES,3
HOLIDAYS/DAYLIGHT SAVING,No,0,0,0
COMMENTS 1,Period of Record=1999-2018
COMMENTS 2,Generated by EPW Insights
DATA PERIODS,1,1,Data,Sunday,1/ 1,12/31
1999,1,1,1,60,C9C9C9*9*0*9*0*9*9*9*9*9*0*0*0*0*9*0*0*0*0*0,10.0,5.0,70.0,101325.0,0,0,0,0,0,0,0,0,0,0,180.0,2.5,9,9,9,9,9,9,9,9,9,9,9,9,9`;

    const result = parseEPW(mockEpw);
    expect(result.metadata.location.city).toBe('Tehran');
    expect(result.metadata.location.country).toBe('IRN');
    expect(result.metadata.location.latitude).toBe(35.68);
    expect(result.data.length).toBe(1);
    expect(result.data[0].dryBulbTemperature).toBe(10.0);
  });
});